# Generated by Django 4.2.4 on 2024-06-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('playlist', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=50)),
                ('like', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
    ]
